name: 'Image Promote to Prod'
description: 'Image Promote to Prod'
inputs:
  reponame:
    description: 'repo name of current deployment'
    required: true
  hubusername:
    description: 'dockerhub username'
    required: true
  hubpassword:
    description: 'dockerhub password or token'
    required: true
  sourcetag:
    description: 'the source tag that needs to be promoted'
    required: true
  targettag:
    description: 'target tag that will be available after promoted'
    required: false
    default: latest

outputs:
  repowithpromotedtag:
    description: "New tag for the deployment"
    value: ${{ steps.inal-promoted-tag.outputs.repowithpromotedtag }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.hubusername }}
        password: ${{ inputs.hubpassword }}
      if: ${{ github.event_name == 'push' }}

    - name: Pull existing image
      run: docker pull ${{ inputs.hubusername }}/${{ inputs.reponame}}:${{ inputs.sourcetag}}
      shell: bash

    - name: Tag the image with new tag
      run: docker tag ${{ inputs.hubusername }}/${{ inputs.reponame}}:${{ inputs.sourcetag}} ${{ inputs.hubusername }}/${{ inputs.reponame}}:${{ inputs.targettag}}
      shell: bash

    - name: Push tagged image to Docker Hub
      run: docker push ${{ inputs.hubusername }}/${{ inputs.reponame}}:${{ inputs.targettag}}
      shell: bash

    - name: Build Tag Output
      id: final-promoted-tag
      run: |
        echo "repowithpromotedtag=$(echo ${{ inputs.hubusername }}/${{ inputs.reponame }}:${{ inputs.targettag }})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

